---
apiVersion: v1
kind: Namespace
metadata:
  name: development

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linuxserver-defaults
  namespace: development
data:
  TZ: Asia/Jerusalem
  PUID: "1000"
  PGID: "1000"
