apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-ingress
  namespace: development
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - zero-ml.com
    - '*.zero-ml.com'
    secretName: zml-certs
  rules:
  - host: private.zero-ml.com
    http:
      paths:
      - path: /notify/
        pathType: Exact
        backend:
          service:
            name: apprise-private
            port:
              number: 8000
  - host: home.zero-ml.com
    http:
      paths:
      - path: /notify/
        pathType: Exact
        backend:
          service:
            name: apprise-home
            port:
              number: 8000